service: pizzaexercise


provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDER_QUEUE:
      Ref: PendingOrdersQueue

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:*:PendingOrdersQueue"
    

functions:
  makeAnOrder:
    handler: handler.makeAnOrder
    events:
      - http:
          method: post
          path: orders
          
resources:
  Resources:
    PendingOrdersQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "PendingOrdersQueue"
